version: "2.2"

services:
  es-proxy:
    container_name: "esd_nginx_elasticsearch-proxy"
    image: "nginx:latest"
    cpu_count: 1
    cpu_period: 50000
    cpu_quota: 48000
    env_file: [".env"]
    volumes:
      - "./cert-bundle:$NGINX_CERTS_DIR"
      - "./nginx/es-proxy.conf:/etc/nginx/conf.d/es-proxy.conf:ro"
    ports: ["19200:9200"]

  web:
    container_name: "esd_nginx_web_kibana-proxy"
    image: "nginx:latest"
    cpu_count: 1
    cpu_period: 50000
    cpu_quota: 48000
    env_file: [".env"]
    volumes:
      - "./cert-bundle:$NGINX_CERTS_DIR"
      - "./nginx/web.conf:/etc/nginx/conf.d/web.conf:ro"
      - "./nginx/html:/etc/nginx/html:ro"
    ports: ["443:8080"]

  elasticsearch:
    container_name: "esd_elasticsearch-internal-7.2.0"
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.2.0"
    cpu_count: 1
    cpu_period: 50000
    cpu_quota: 40000
    ulimits:
      memlock:
        soft: -1
        hard: -1
    env_file: [".env"]
    environment:
      - "cluster.name=esd"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "xpack.watcher.enabled=false"
      - "xpack.security.enabled=true"
      - "xpack.security.http.ssl.certificate=$ES_CERTS_DIR/virtual-spice/virtual-spice.crt"
      - "xpack.security.http.ssl.enabled=true"
      - "xpack.security.http.ssl.key=$ES_CERTS_DIR/virtual-spice/virtual-spice.key"
      - "xpack.security.transport.ssl.enabled=true"
      - "xpack.security.transport.ssl.verification_mode=certificate"
      - "ELASTIC_PASSWORD=$ELASTIC_PASSWORD"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "./cert-bundle:$ES_CERTS_DIR"
      - "esdata-7.2:/usr/share/elasticsearch/data"

  kibana:
    container_name: "esd_kibana-7.2.0"
    image: "docker.elastic.co/kibana/kibana:7.2.0"
    cpu_period: 50000
    cpu_quota: 45000
    env_file: [".env"]
    environment:
      - "SERVER_BASEPATH=/kibana"
      - "SERVER_HOST=kibana"
      - "LOGGING_VERBOSE=true"
      - "ELASTICSEARCH_URL=$ELASTICSEARCH_HOSTS"
      - "ELASTICSEARCH_USERNAME=$KBN_ES_USERNAME"
      - "ELASTICSEARCH_PASSWORD=$KBN_ES_PASSWORD"
      - "ELASTICSEARCH_SSL_KEY=$KBN_CERTS_DIR/virtual-spice/virtual-spice.key"
      - "ELASTICSEARCH_SSL_CERTIFICATE=$KBN_CERTS_DIR/virtual-spice/virtual-spice.crt"
      - "ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=$KBN_CERTS_DIR/ca/virtual-spice-ca.crt"
      - "ELASTICSEARCH_SSL_VERIFICATIONMODE=certificate"
      - "XPACK_REPORTING_CAPTURE_BROWSER_TYPE=chromium"
      - "XPACK_REPORTING_QUEUE_POLLINTERVAL=30000"
      - "XPACK_REPORTING_KIBANASERVER_PORT=8080"
      - "XPACK_REPORTING_KIBANASERVER_PROTOCOL=https"
      - "XPACK_REPORTING_KIBANASERVER_HOSTNAME=web"
      - "XPACK_SECURITY_SESSIONTIMEOUT=3600000"
      - "XPACK_REPORTING_ENCRYPTIONKEY=$SESSION_SECRET"
      - "XPACK_SECURITY_ENCRYPTIONKEY=$SESSION_SECRET"
    volumes: ["./cert-bundle:$KBN_CERTS_DIR"]

  metricbeat:
    container_name: "esd_metricbeat-7.2.0"
    image: "docker.elastic.co/beats/metricbeat:7.2.0"
    user: "root"
    cpu_count: 1
    cpu_period: 50000
    cpu_quota: 35000
    env_file: [".env"]
    environment:
      - "DOCKER_HOST=unix:///var/run/docker.sock"
      - "ELASTICSEARCH_URL=$ELASTICSEARCH_HOSTS"
      - "ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=$METRICBEAT_CERTS_DIR/ca/virtual-spice-ca.crt"
      - "METRICBEAT_KBN_SETUP_USERNAME=$METRICBEAT_KBN_SETUP_USERNAME"
      - "METRICBEAT_KBN_SETUP_PASSWORD=$METRICBEAT_KBN_SETUP_PASSWORD"
    volumes:
      - "./cert-bundle:$METRICBEAT_CERTS_DIR"
      - "./metricbeat/config:/usr/share/metricbeat/config:ro"
      - "./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"

  apm-server:
    container_name: "esd_apm-server-7.2.0"
    image: "docker.elastic.co/apm/apm-server:7.2.0"
    cpu_count: 1
    cpu_period: 50000
    cpu_quota: 35000
    env_file: [".env"]
    environment:
      - "ELASTICSEARCH_URL=$ELASTICSEARCH_HOSTS"
      - "ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=$APM_CERTS_DIR/ca/virtual-spice-ca.crt"
    command: "apm-server -e -E apm-server.host=0.0.0.0:8200"
    volumes:
      - "./cert-bundle:$APM_CERTS_DIR"
      - "./apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro"
    ports: ["8200:8200"]

  curator:
    container_name: "esd_curator-5.5"
    image: "tsullivan/curator-5.5"
    build: "./curator"
    env_file: [".env"]
    environment:
      - "ELASTICSEARCH_HOST=$CURATOR_CLIENT_HOST"
      - "CLIENT_HOST=$CURATOR_CLIENT_HOST"
      - "CLIENT_PORT=9200"
      - "MAX_INDEX_AGE=3"
    volumes:
      - "./cert-bundle:$CURATOR_CERTS_DIR"
      - "./curator/delete-indices.yml:/usr/share/curator/delete-indices.yml:ro"
      - "./curator/curator.yml:/usr/share/curator/curator.yml"

  chatbot:
    container_name: "esd_my-chatbot"
    image: "tsullivan/chatbot"
    build: "$HOME/code/chatbot"
    cpu_period: 50000
    cpu_quota: 45000
    env_file: [".env"]
    environment:
      - "SLACK_BOT_TOKEN=$BOT_SLACK_BOT_TOKEN"
      - "APM_TOKEN=$BOT_ELASTIC_APM_TOKEN"
      - "APM_URL=$BOT_ELASTIC_APM_SERVER_URL"
      - "SESSION_SECRET=$SESSION_SECRET"

volumes:
  esdata-7.2:
    driver: "local"
