version: "2.2"

services:
  es-proxy:
    container_name: "esd_nginx_elasticsearch-proxy"
    image: "nginx"
    cpu_count: 1
    cpu_period: 50000
    cpu_quota: 48000
    env_file: [".env"]
    volumes:
      - "./cert-bundle:$NGINX_CERTS_DIR"
      - "./nginx/es-proxy.conf:/etc/nginx/conf.d/es-proxy.conf:ro"
    ports: ["19200:9200"]

  web:
    container_name: "esd_nginx_web_kibana-proxy"
    image: "nginx"
    cpu_count: 1
    cpu_period: 50000
    cpu_quota: 48000
    env_file: [".env"]
    volumes:
      - "./cert-bundle:$NGINX_CERTS_DIR"
      - "./nginx/web.conf:/etc/nginx/conf.d/web.conf:ro"
      - "./nginx/html:/etc/nginx/html:ro"
    ports: ["443:8080"]

  elasticsearch:
    container_name: "esd_elasticsearch-internal-6.4.0"
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.4.0"
    cpu_count: 1
    cpu_period: 50000
    cpu_quota: 40000
    ulimits:
      memlock:
        soft: -1
        hard: -1
    env_file: [".env"]
    environment:
      - "cluster.name=esd"
      - "bootstrap.memory_lock=true"
      - "xpack.license.self_generated.type=trial"
      - "xpack.security.enabled=true"
      - "xpack.security.http.ssl.enabled=true"
      - "xpack.security.transport.ssl.enabled=true"
      - "xpack.ssl.key=$ES_CERTS_DIR/virtual-spice/virtual-spice.key"
      - "xpack.ssl.certificate=$ES_CERTS_DIR/virtual-spice/virtual-spice.crt"
      - "xpack.ssl.certificate_authorities=$ES_CERTS_DIR/ca/virtual-spice-ca.crt"
      - "xpack.security.transport.ssl.verification_mode=certificate"
      - "ELASTIC_PASSWORD=$ELASTIC_PASSWORD"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "./cert-bundle:$ES_CERTS_DIR"
      - "esdata-6.3:/usr/share/elasticsearch/data"

  kibana:
    container_name: "esd_kibana-canvas-6.4.0"
    build: "kibana"
    cpu_period: 50000
    cpu_quota: 45000
    env_file: [".env"]
    environment:
      - "SERVER_BASEPATH=/kibana"
      - "SERVER_HOST=kibana"
      - "ELASTICSEARCH_URL=$ELASTICSEARCH_URL"
      - "ELASTICSEARCH_USERNAME=$KBN_ES_USERNAME"
      - "ELASTICSEARCH_PASSWORD=$KBN_ES_PASSWORD"
      - "ELASTICSEARCH_SSL_KEY=$KBN_CERTS_DIR/virtual-spice/virtual-spice.key"
      - "ELASTICSEARCH_SSL_CERTIFICATE=$KBN_CERTS_DIR/virtual-spice/virtual-spice.crt"
      - "ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=$KBN_CERTS_DIR/ca/virtual-spice-ca.crt"
      - "ELASTICSEARCH_SSL_VERIFICATIONMODE=certificate"
      - "XPACK_REPORTING_ENCRYPTIONKEY=$SESSION_SECRET"
      - "XPACK_SECURITY_ENCRYPTIONKEY=$SESSION_SECRET"
      - "XPACK_SECURITY_SESSIONTIMEOUT=600000"
    volumes:
      - "./cert-bundle:$KBN_CERTS_DIR"
      - "esdata-6.3:/usr/share/elasticsearch/data"

  metricbeat:
    container_name: "esd_metricbeat-6.4.0"
    image: "docker.elastic.co/beats/metricbeat:6.4.0"
    user: "root"
    cpu_count: 1
    cpu_period: 50000
    cpu_quota: 35000
    env_file: [".env"]
    environment:
      - "DOCKER_HOST=unix:///var/run/docker.sock"
      - "ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=$METRICBEAT_CERTS_DIR/ca/virtual-spice-ca.crt"
    volumes:
      - "./cert-bundle:$METRICBEAT_CERTS_DIR"
      - "./metricbeat/config:/usr/share/metricbeat/config:ro"
      - "./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"

  apm-server:
    container_name: "esd_apm-server-6.4.0"
    image: "docker.elastic.co/apm/apm-server:6.4.0"
    cpu_count: 1
    cpu_period: 50000
    cpu_quota: 35000
    env_file: [".env"]
    environment:
      - "ELASTICSEARCH_URL=$ELASTICSEARCH_URL"
      - "ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=$APM_CERTS_DIR/ca/virtual-spice-ca.crt"
    volumes:
      - "./cert-bundle:$APM_CERTS_DIR"
      - "./apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro"
    ports: ["8200:8200"]

  logstash:
    container_name: "esd_logstash-6.4.0"
    image: "docker.elastic.co/logstash/logstash:6.4.0"
    cpu_count: 1
    cpu_period: 50000
    cpu_quota: 45000
    env_file: [".env"]
    environment:
      - "ELASTICSEARCH_URL=$ELASTICSEARCH_URL"
      - "ELASTICSEARCH_SSL_CERTIFICATE=$LOGSTASH_CERTS_DIR/virtual-spice/virtual-spice.crt"
      - "XPACK_MONITORING_ENABLED=true"
      - "XPACK_MONITORING_ELASTICSEARCH_URL=$ELASTICSEARCH_URL"
    volumes:
      - "./cert-bundle:$LOGSTASH_CERTS_DIR"
      - "./logstash/pipeline:/usr/share/logstash/pipeline:ro"
      - "./logstash/avocado-tweets-wildcard.json:/usr/share/logstash/avocado-tweets-wildcard.json:ro"

  curator:
    container_name: "esd_curator-5.5"
    image: "tsullivan/curator-5.5"
    build: "./curator"
    env_file: [".env"]
    environment:
      - "CLIENT_HOST=$CURATOR_CLIENT_HOST"
      - "CLIENT_PORT=9200"
      - "MAX_INDEX_AGE=3"
    volumes:
      - "./cert-bundle:$CURATOR_CERTS_DIR"
      - "./curator/delete-indices.yml:/usr/share/curator/delete-indices.yml:ro"
      - "./curator/curator.yml:/usr/share/curator/curator.yml"

  chatbot:
    container_name: "esd_my-chatbot"
    image: "tsullivan/chatbot"
    build: "$HOME/code/chatbot"
    cpu_period: 50000
    cpu_quota: 45000
    env_file: [".env"]
    environment:
      - "SESSION_SECRET=$SESSION_SECRET"
      - "ELASTIC_APM_SERVER_URL=$APM_SERVER_URL"

volumes:
  esdata-6.3:
    driver: "local"
