metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["${DOCKER_HOST}"]
  period: 10s
  enabled: true

  # Replace dots in labels with `_`. Set to false to keep dots
  labels.dedot: true

setup.template.fields: "config/fields.yml"

output.elasticsearch:
  hosts: "${ELASTICSEARCH_URL}"
  username: "${BEATS_WRITER_ES_USERNAME}"
  password: "${BEATS_WRITER_ES_PASSWORD}"
  ssl.certificate_authorities: ["${ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES}"]

xpack.monitoring:
  enabled: true
  elasticsearch:
    username: "${BEATS_SYSTEM_ES_USERNAME}"
    password: "${BEATS_SYSTEM_ES_PASSWORD}"
