---
client:
  hosts: 
    - ${CLIENT_HOST}
  port: ${CLIENT_PORT}
  http_auth: ${CURATOR_ES_USERNAME}:${CURATOR_ES_PASSWORD}
  use_ssl: True
  ssl_no_validate: True

logging:
  loglevel: "INFO"
  logformat: "default"
  blacklist: ["elasticsearch", "urllib3"]
